### ISSUE TITLE
Routing Code is Suboptimal

### ISSUE THREAD

**Issue by rbhog** [cloud-systems/webApp#2]
I believe that while looking through the code, I noticed that routing between pages is not handled in the most efficient manner. A prestigious society such as that of Cloud Systems should not be seen with such a rookie level mistake. I refuse to let the integrity of this organization fall to pieces with such a small error and therefore have proposed a solution which can be found in PR #1 

God bless this institution and members of it.

~rbhog

**Comment by cf12** [comment]
God bless this institution and members of it.

~CF12

**Comment by notjasonl** [comment]
God bless this institution and members of it.

~notjasonl

**Comment by chiumax** [comment]
God bless this institution and members of it.

~chiumax
